linter:
  rules:
    #- avoid_dynamic_calls
    - always_specify_types
    - avoid_unnecessary_containers
    - unnecessary_statements
    - prefer_conditional_assignment
    - curly_braces_in_flow_control_structures
    - flutter_style_todos
    - join_return_with_assignment
    - prefer_single_quotes
    - avoid_returning_null_for_future
    - avoid_returning_null
    - unnecessary_this
    - sized_box_for_whitespace
    - always_use_package_imports
    - avoid_relative_lib_imports
    - lines_longer_than_80_chars
