name: noor
description: أذكار وأدعية من كتاب حصن المسلم

version: 2.4.0+36

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^1.1.1
  firebase_messaging: ^9.1.4
  firebase_remote_config: ^0.10.0-dev.3

  # Data
  get_it: ^7.1.3
  intl: ^0.17.0
  share: ^2.0.1
  sqflite: ^2.0.0+3
  provider: ^5.0.0
  url_launcher: ^6.0.3
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  flutter_local_notifications: ^5.0.0+4

  # Look
  animations: ^2.0.0
  flutter_svg: ^0.22.0
  reorderables: ^0.4.1
  flutter_datetime_picker: ^1.5.1
  scrollable_positioned_list: ^0.2.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/launcher_icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/launcher_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/ribbons/
    - assets/images/social-buttons/
    - assets/images/home-header/
    - assets/images/home-cards/light/
    - assets/images/home-cards/dark/
    - assets/images/backgrounds/
    - assets/images/fav-buttons/
    - assets/icons/
    - assets/icons/ad3yah/
    - assets/json/

  fonts:
    - family: SST Arabic
      fonts:
        - asset: assets/fonts/SST-Light.ttf
          weight: 200
        - asset: assets/fonts/SST-Arabic-Roman.ttf
          weight: 400
        - asset: assets/fonts/SST-Arabic-Medium.ttf
          weight: 700
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Regular.ttf
    - family: Geeza
      fonts:
        - asset: assets/fonts/Geeza-Pro-Regular.ttf
    - family: NoorIcons
      fonts:
        - asset: assets/fonts/NoorIcons.ttf
    - family: NoorSettingsIcons
      fonts:
        - asset: assets/fonts/NoorSettingsIcons.ttf
